
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b1fc3492e7ea8aa822f1c0993fcd38c485a6b61e",
 "version": "5.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
